"All versions to manage"
VERSION = "8.0.3"
ANGULAR_PACKAGE_VERSION = "^10.0.0 || ^11.0.0-0"

VERSION_PLACEHOLDER_REPLACEMENTS = {
    "{{VERSION}}": VERSION,
    "{{NG_VERSION}}": ANGULAR_PACKAGE_VERSION,
}
